In [2]:
import pandas
import sklearn.model_selection

In [3]:
data_train_test = pandas.read_csv('./data/high_salary.csv').set_index('id')
data_train_test

,social-security-number,house-number,age-group,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country-code,native-country,label
id,,,,,,,,,,,,,,,,,,
8616,552701574.0,9854.0,2.0,self-emp-inc,270079.0,bachelors,13.0,married-civ-spouse,exec-managerial,husband,white,male,0.0,0.0,3.0,USA,united-states,1.0
21982,956556990.0,7588.0,3.0,local-gov,146325.0,doctorate,16.0,married-civ-spouse,prof-specialty,husband,white,male,0.0,2.0,2.0,USA,united-states,1.0
11191,958358623.0,6729.0,0.0,private,240767.0,hs-grad,9.0,never-married,other-service,not-in-family,white,female,0.0,0.0,1.0,USA,united-states,0.0
22229,224206693.0,6288.0,2.0,private,118536.0,hs-grad,9.0,divorced,machine-op-inspct,other-relative,black,male,0.0,0.0,2.0,USA,united-states,0.0
20732,276413230.0,8276.0,3.0,private,160440.0,bachelors,13.0,married-civ-spouse,sales,husband,white,male,0.0,0.0,3.0,USA,united-states,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21575,263539011.0,7910.0,0.0,private,147253.0,assoc-acdm,12.0,never-married,sales,not-in-family,white,male,0.0,0.0,2.0,USA,united-states,0.0
5390,590882568.0,6432.0,3.0,private,330543.0,preschool,1.0,married-civ-spouse,other-service,husband,white,male,0.0,0.0,2.0,MEX,mexico,0.0
860,289157658.0,2008.0,3.0,private,41223.0,some-college,10.0,married-civ-spouse,adm-clerical,husband,white,male,0.0,0.0,2.0,USA,united-states,1.0
15795,363933621.0,4726.0,0.0,state-gov,275421.0,some-college,10.0,never-married,machine-op-inspct,own-child,white,female,0.0,0.0,2.0,USA,united-states,0.0
23654,185635080.0,5278.0,4.0,private,177271.0,masters,14.0,married-civ-spouse,exec-managerial,husband,white,male,0.0,0.0,3.0,USA,united-states,1.0

In [5]:
data_train, data_test = sklearn.model_selection.train_test_split(
    data_train_test, 
    train_size   = 0.75, 
    shuffle      = True, 
    random_state = 0
)
data_train.to_csv('./data/high_salary.train.csv')
data_test.to_csv('./data/high_salary.test.csv')