In [1]:
import numpy
import pandas
import joblib
import json
import seaborn
import sklearn

%matplotlib inline

# Instructions

- Read **the test data** from the CSV file and properly set the index
- Load the trained model

In [2]:
data_test= pandas.read_csv('./data/features.test.csv').set_index('id')
data_test

,fnlwgt,age-group,education-num,capitalgain,capitalloss,hoursperweek,workclass_self-emp-not-inc,workclass_private,workclass_self-emp-inc,workclass_local-gov,...,native-country_honduras,native-country_thailand,native-country_laos,native-country_peru,native-country_holand-netherlands,native-country_haiti,native-country_scotland,sex_male,sex_female,label
id,,,,,,,,,,,,,,,,,,,,,
12849,3.059280,1.0,12.0,2.0,0.0,2.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1460,0.513775,0.0,0.0,0.0,0.0,3.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13594,-0.431650,2.0,8.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14400,-0.369947,3.0,8.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14333,-0.509173,2.0,8.0,0.0,0.0,3.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,1.502472,1.0,11.0,0.0,0.0,3.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2952,-1.293459,2.0,11.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
9470,-0.618671,4.0,15.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
16559,-0.401205,4.0,8.0,0.0,4.0,2.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
27733,1.691348,2.0,8.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [3]:
model = joblib.load('./model/logistic_regression_model.joblib')
model

LogisticRegression(C=2, class_weight='balanced', fit_intercept=False,
                   random_state=0)


# Instructions

- Calculate and add the `prediction` column to the dataframe of test data
- Compare the labels with the predictions and put them into 4 `result_type` categories; namely,
  - true_negative
  - false_negative
  - true_positive
  - false_positive
- Add the `result_type` column to the dataframe of test data
- Write the dataframe to `./results/predictions.test.csv`

In [4]:
data_test['prediction'] = model.predict(
     X= data_test.drop(columns=['label']),
)
data_test

,fnlwgt,age-group,education-num,capitalgain,capitalloss,hoursperweek,workclass_self-emp-not-inc,workclass_private,workclass_self-emp-inc,workclass_local-gov,...,native-country_thailand,native-country_laos,native-country_peru,native-country_holand-netherlands,native-country_haiti,native-country_scotland,sex_male,sex_female,label,prediction
id,,,,,,,,,,,,,,,,,,,,,
12849,3.059280,1.0,12.0,2.0,0.0,2.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
1460,0.513775,0.0,0.0,0.0,0.0,3.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
13594,-0.431650,2.0,8.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
14400,-0.369947,3.0,8.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
14333,-0.509173,2.0,8.0,0.0,0.0,3.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,1.502472,1.0,11.0,0.0,0.0,3.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2952,-1.293459,2.0,11.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
9470,-0.618671,4.0,15.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
16559,-0.401205,4.0,8.0,0.0,4.0,2.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
27733,1.691348,2.0,8.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [5]:
result_types =[
    {
        'prediction' : 0,
        'label' : 0,
        'result_type': 'true_negative'
    },
    {
        'prediction' : 1,
        'label' : 0,
        'result_type': 'false_positive'
    },
    {
        'prediction' : 0,
        'label' : 1,
        'result_type': 'false_negative'
    },
    {
        'prediction' : 1,
        'label' : 1,
        'result_type': 'true_positive'
    },
]

In [6]:
result_types = pandas.DataFrame(result_types).set_index(['prediction', 'label'])
result_types

                     result_type
prediction label
0          0       true_negative
1          0      false_positive
0          1      false_negative
1          1       true_positive

In [7]:
data_test = data_test.join(result_types, on = ['prediction', 'label'], how = 'left')
data_test

,fnlwgt,age-group,education-num,capitalgain,capitalloss,hoursperweek,workclass_self-emp-not-inc,workclass_private,workclass_self-emp-inc,workclass_local-gov,...,native-country_laos,native-country_peru,native-country_holand-netherlands,native-country_haiti,native-country_scotland,sex_male,sex_female,label,prediction,result_type
id,,,,,,,,,,,,,,,,,,,,,
12849,3.059280,1.0,12.0,2.0,0.0,2.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,true_positive
1460,0.513775,0.0,0.0,0.0,0.0,3.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,true_negative
13594,-0.431650,2.0,8.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,true_negative
14400,-0.369947,3.0,8.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,true_negative
14333,-0.509173,2.0,8.0,0.0,0.0,3.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,true_positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,1.502472,1.0,11.0,0.0,0.0,3.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,true_negative
2952,-1.293459,2.0,11.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,true_positive
9470,-0.618671,4.0,15.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,true_positive
16559,-0.401205,4.0,8.0,0.0,4.0,2.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,true_negative
27733,1.691348,2.0,8.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,true_negative

In [8]:
data_test.to_csv('./results/logistic_regression_predictions.test.csv')

In [9]:
report = sklearn.metrics.classification_report(
    y_true=data_test['label'],
    y_pred=data_test['prediction'],
    output_dict=True  # Get the report in dictionary format
)

# Convert the dictionary to a pandas DataFrame
report_df = pandas.DataFrame(report).transpose()
print(report_df)

              precision    recall  f1-score      support
0.0            0.873265  0.788328  0.828626  3033.000000
1.0            0.741858  0.841697  0.788630  2192.000000
accuracy       0.810718  0.810718  0.810718     0.810718
macro avg      0.807561  0.815013  0.808628  5225.000000
weighted avg   0.818137  0.810718  0.811847  5225.000000

In [10]:
confusion_matics_from_sklearn = sklearn.metrics.confusion_matrix(
    y_true = data_test['label'],
    y_pred = data_test['prediction'],
)
confusion_matics_from_sklearn

array([[2391,  642],
       [ 347, 1845]])

In [11]:
scores = {
    "true_positive": 1845,
    "true_negative": 2391,
    "false_negative": 347,
    "false_positive": 642,
    "accuracy": 0.810718,
    "precision": 0.741858,
    "recall": 0.841697,
    "support": 2192,
    "f1-score": 0.788630
}

In [12]:
with open('./results/logistic_regression_scores.test.json', 'w') as f:
    json.dump(scores, f)